### ISSUE TITLE
Compiling Code Throws Errors

### ISSUE THREAD

**Issue by mserlin** [afylab/Electronics#3]
It throws the error "redefinition of int adc" and highlights in red line the sixth line of code. I don't know what this means.

**Comment by ckometter** [comment]
I do not get  that error:

- Try updating the arduino IDE.
- Make sure there is no other sketch in the same folder.
- Make sure you're on the master branch.

If you keep getting the same error, post the whole error.

**Comment by mserlin** [comment]
The error was not reproducible. Weird, problem solved I guess!
